apps/portfolio/urls.py
from django.urls import path
from apps.portfolio import views


urlpatterns = [
    path('', views.HomeView.index, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.portfolio.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apps/portfolio/models/About.py
from . import *


class About(models.Model):
    heading = models.CharField(
        max_length=100,
    )
    career = models.CharField(
        max_length=50,
    )
    description = models.TextField(
        blank=False,
    )
    profile_img = models.ImageField(
        upload_to='media/profile/',
    )
    updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.career

apps/portfolio/models/Category.py
from . import *


class Category(models.Model):
    name = models.CharField(
        max_length=50,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

apps/portfolio/models/Home.py
from . import *


class Home(models.Model):
    name = models.CharField(
        max_length=100,
    )
    greettings_1 = models.CharField(
        max_length=10,
    )
    greettings_2 = models.CharField(
        max_length=10,
    )
    picture = models.ImageField(
        upload_to='picture/',
    )
    email = models.EmailField(
        null=True,
    )
    phone = models.CharField(
        max_length=20, null=True,
    )
    address = models.CharField(
        max_length=30, null=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

apps/portfolio/models/Portfolio.py
from . import *


class Portfolio(models.Model):
    image = models.ImageField(
        upload_to='portfolio/',
    )
    github = models.CharField(
        max_length=254, null=True,
    )
    link = models.CharField(
        max_length=254,
    )

    def __str__(self):
        return f'Portfolio {self.id}'

apps/portfolio/models/Profile.py
from . import *


class Profile(models.Model):
    about = models.ForeignKey(
        About, on_delete=models.CASCADE,
    )
    social_name = models.CharField(
        max_length=20,
    )
    link = models.CharField(
        max_length=254,
    )

apps/portfolio/models/Skills.py
from . import *


class Skills(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE,
    )
    skill_name = models.CharField(
        max_length=50,
    )

apps/portfolio/views/HomeView.py
from . import *


def index(request):
    # Home
    home = Home.objects.latest('updated')

    # About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

    # Skills
    categories = Category.objects.all()

    # Portfolio
    portfolios = Portfolio.objects.all()

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios,
    }

    return render(request, 'apps.portfolio/index.html', context)

templates/apps.portfolio/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>{{ home.name }} Website</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                <div>
                    <a href="#" class="nav__logo">{{home.name}}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">Sobre mim</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfólio</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Me ache!</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{home.greettings_1}}</span><br><span>{{home.greettings_2}}</span></h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{home.picture.url}}" alt="" class="home__img">
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">Sobre mim</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{{ about.profile_img.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description }}</p>

                        <div class="about__social">
                            {% for profile in profiles %}
                            <a href="{{profile.link}}" class="about__social-icon"><i class="bx bxl-{{profile.social_name}}" ></i></a>
                            
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>
                
                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        <div class="skills__box">
                            
                            {% for category in categories %}
                            <h3 class="skills__subtitle">{{category.name}}</h3>
                            
                            {% for skills in category.skills_set.all %}
                            <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                            
                            {% endfor %}
                        
                        </div>
                    </div>
                    <div class="skills__img">
                        <img src="{% static 'assets/img/skill.jpg' %}" alt="">
                    </div>
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Portfólio</h2>

                <div class="portfolio__container bd-grid">
                {% for portfolio in portfolios %}
                    <div class="portfolio__img">
                        <img src="{{portfolio.image.url}}" alt="">

                        <div class="portfolio__link">
                            <strong>
                            <a href="{{portfolio.github}}" class="portfolio__link-name" target="_blank">Ver Detalhes / Repositório<a><br><br>
                            <a href="{{portfolio.link}}" class="portfolio__link-name" target="_blank">Ver site/app publicado</a>
                            </strong>
                        </div>
                        <!-- <div class="portfolio__link">
                            <a href="{{portfolio.github}}">Repositório no GITHUB</a>
                        </div> -->
                    </div>
                {% endfor %}

                </div>
            </section>

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Me ache!</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">MEU EMAIL</h3>
                        <span class="contact__text"><a href="mailto:{{home.email}}">{{home.email}}</a></span>

                        <h3 class="contact__subtitle">MEU NÚMERO (VOZ/WHATS)</h3>
                        <span class="contact__text">{{home.phone}}</span>

                        <h3 class="contact__subtitle">MINHA HUMILDE RESIDÊNCIA</h3>
                        <span class="contact__text">{{home.address}}</span>
                    </div>

                    <form action="" class="contact__form">
                        <div class="contact__inputs">
                            <input type="text" placeholder="Escreva seu nome ..." class="contact__input">
                            <input type="mail" placeholder="Escreva seu Email" class="contact__input">
                        </div>

                        <textarea name="" placeholder="Escreva sua mensagem aqui ..." id="" cols="0" rows="10" class="contact__input"></textarea>

                        <input type="submit" value="Enviar" class="contact__button">
                    </form>
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title"><a href="#home">{{ home.name | upper }}</a></h2>
                    <p class="footer__text">Eu sou {{home.name}} e este é meu website para apresentação profissional. </p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">Sobre</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">Portfólio</a></li>
                        <li><a href="#Contact" class="footer__link">Me ache!</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    
                    <h2 class="footer__title">ME ENCONTRE!</h2>
                    {% for profile in profiles %}
                    <a href="{{profile.link}}" target="_blank" rel="noopener noreferrer" class="footer__social"><i class="bx bxl-{{profile.social_name}}"></i></a>
                    {% endfor %}
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>